### ISSUE TITLE
Please add a github pages link

### ISSUE THREAD

**Issue by bovas85** [NityaSriAdapala/Project-GirlsCanCode#16]
Hi there, we'd like to show your site in a medium blog post. 

Can you activate the github pages on master?

**Comment by NityaSriAdapala** [comment]
https://nityasriadapala.github.io/Project-GirlsCanCode/

Above is the link for the webpage. I sincerely apologise that it is so late, I was on the CyberFirst Futures Residential, so unfortunately I couldn't send the link. 

Also, when I open the webpage as a file after downloading it, the pictures in the slideshow and on each of the days in Our Story come up, but when I click the above link some of the pictures don't come up and the background on the Our Story page isn't completely pink. I don't know how to resolve these issues. Sorry...

Nitya :)

**Comment by bovas85** [comment]
No apologies needed! Thank you for sending the link and good work with your possibly first closed issue on github :)

**Comment by bovas85** [comment]
Regarding the image, you are loading it from the css folder rather than images folder
(https://nityasriadapala.github.io/Project-GirlsCanCode/css/Classroom3.JPEG) ->
(https://nityasriadapala.github.io/Project-GirlsCanCode/images/Classroom3.JPEG)

**Comment by bovas85** [comment]
for our story, remove the height in pixels to the .square class 
```
.square {
  /* height: 200px; remove this */
  width: 1365px;
  background-color: white;
}
```

**Comment by NityaSriAdapala** [comment]
Hello!
I resolved the issue with the slideshow but the background for the our story page is still not becoming pink..., is there another way to solve it?
Thank you,
Nitya

**Comment by NityaSriAdapala** [comment]
Actually don't worry, I just changed the background colour of another element, so it's all fixed now, except for the fact that some of the pictures aren't showing up...

**Comment by NityaSriAdapala** [comment]
Actually wait I got it all fixed, it just took some time for it to load. Our website is finished now, thank you for all your help!

Nitya

**Comment by bovas85** [comment]
Good job!

**Comment by bovas85** [comment]
Can you add your website link to the readme?

**Comment by bovas85** [comment]
You can create a readme.md file in the root of the project and use markdown to describe the project and link to the live website. :+1:

**Comment by NityaSriAdapala** [comment]
Yep, I have just added the README.md file. Thank you!
